### PR TITLE
Sandbox Graphs and Componentization

### PR DESCRIPTION
**Pull request by amcguiga**
This is contingent on https://github.com/astoria-tech/50-a-foil-status/pull/74

## Overview

- Reorganize each of the graphs into components for better compartmentalization
- Standardize the data parsing process on the frontend to common patterns
- Introduce consistent data ranges: `TurnaroundTime`, `FeeRange` (and the existing `FoiaStatus`)
- Rework the existing turnaround time graph to extend time range and add `Outstanding`
- Rework fee graph so that it's actually graphing fee ranges rather than unique fees
- Introduce React Router to allow for multiple pages
- Add a Sandbox page at a hidden route `/sandbox` for all in progress graphs
- Add the treemap demo to sandbox
- Add two funnel status graphs (Happy Path and Unhappy Path) to sandbox
- Add a pie graph of statuses
- Add a sankey graph of statuses

## Reorg
I added a `pages` construct to handle the existing `Home` page and the new `Sandbox` page. These take in the api data as a property and pass it to the necessary graphs. These do not contain the `Header` or `Footer` or `Menu` - those can still be initialized at the main `App` level as it's shared content. 

I moved all graphs into their own components which contain the data parsing logic for that specific graph and the logic to render them in nivo. The contract to initialize them is:
```
  <GraphType
    data = {dataFromTheApi}
  />
```

_I have not reorganized any CSS._ I do think that we should be breaking it up to be associated with relevant components, but CSS isn't my specialty and what we have does currently work even with these changes because the `App` is still a common toplevel reference. 

I added a new utilities folder to handle the various data constructs. 

- TurnaroundTime
  - Day ranges that it takes a request to go from `datetime_submitted` to `datetime_completed` (incl `Outstanding`)
- FeeRange
  - USD ranges of the fee charged for a request (incl `No Fee`)
- FoiaStatus
  - The different statuses that a Foia request can be in. 
  - This can also be traced through a Foia Request's `communications` attribute which has a history of the status changes.

## Production Changes
As part of standardizing everything, that did mean that I changed up the way that the existing graphs work to make them consistent between filtering the data and rendering the graphs. 

### Turnaround Time 
I'm of the strong opinion that we should emphasize graphically **how many of these requests are still not complete**. I believe it's the most important attribute of the time taken. This reframes the graph by showing how little movement has been made on these requests in aggregate. 
Screen Shot 2021-04-11 at 6 19 57 PM

### Fees
Previously we just showed a bar graph of ascending unique fee values. This is confusing because the data isn't really in aggregate. Thus, I reorganized it around the fee ranges; it shows that many departments are charging reasonable fees, but that there are definitely some _bad apples_.
Screen Shot 2021-04-11 at 6 20 07 PM

If we want to show what % of fees are based on the few bad offenders, maybe we should consider a pie graph or [bubble graph](https://nivo.rocks/bubble/) instead? Happy to take a stab at that as well. 

### Foia List
As part of making all of these ranges consistent, that also means that the Foia List filtering will now filter by ranges rather than basing it on months previous to the current date on the user's local machine. 
Screen Shot 2021-04-11 at 6 20 17 PM

## Sandbox Graphs
These are all WIP naturally, I just want to get the framework out there.

### Status Funnel
I added two funnel graphs about status histories. One looks at the path from `Acknowledged` -> `Processed` -> `Done`, which is the ideal path. The other looks at the different friction points that you can hit such as `Fix` and `Payment`.
Screen Shot 2021-04-11 at 6 18 21 PM

Unfortunately, the funnel graph is a bit wonky for labels, and you have to hover to see them. Trying to mess with that. In addition, there may be an opportunity to update the graph by clicking on it, which I think could be an interesting way of making the data interactive.

### Status Pie
Added a pie graph for statuses. This shows the current status of a request rather than the history - e.g. how many are `Done` vs `No Documents Found`. 
Screen Shot 2021-04-11 at 6 18 06 PM

As with the funnel graph, the labels are funky and require hovering. The radial labels also have a tendency to get hidden very easily, so sizing this one might be a challenge.

### Status Sankey
Sankey graphs are funnel graphs on steriods. I made one to get a really comprehensive view on the status changes over time to help me validate my data cleaning project that I've got ongoing for status data. 
Screen Shot 2021-04-11 at 6 19 03 PM

This might end up being too complex for end-user's to use. Might have to filter out a bunch of steps that aren't super common such as `Appealing`. That said, I think it's awesome for analysis and let's you get a much deeper view on progression for communications over time. That said, it can't capture repeated statuses - such as when multiple `fix` are required for a given Foia Request. It also can't go backwards to earlier listed statuses either. 

## Discussion

- [x] Are y'all all cool with the structure?
- [x] How about the changes in the existing graphs?
- [x] Especially the fee graph, I'm still not happy with my version.
- [x] Should I try to break this PR up? I got a little out of control with it.

### CODE REVIEW

**Comment by aniagaska** [comment]
I think adding the sandbox is a great idea! 

Adding outstanding to the time visualization is great because it shows we have requests that are pending for a long time, and I wonder if there is another way we can show how much time is passing for these agencies without progress.

For the fees, the most important thing to be able to track is who is charging the most money and highlight those, so a bubble graph, or a [swarm plot](https://nivo.rocks/swarmplot/) might be worth trying because we want to show that most people do not charge anything, or much at all and then there are a few that charge a ridiculous amount for their requests without good reasoning behind it.

The fact that you can't see the labels for the graph without hovering is worth looking into further, maybe a separate PR?

**Review by aniagaska — APPROVED** [review]

**Comment by amcguiga** [comment]
> so a bubble graph, or a swarm plot might be worth trying

Makes sense, I might try to add some of those to Sandbox soon as candidates for replacing the current one.

> I wonder if there is another way we can show how much time is passing for these agencies without progress.

Too bad there's not an easy way to make a Napoleon march graph 😭 
https://en.wikipedia.org/wiki/Charles_Joseph_Minard#/media/File:Minard.png

> The fact that you can't see the labels for the graph without hovering is worth looking into further, maybe a separate PR?

Yep! Everything in the sandbox section is WIP - I feel no compunction about checking in unfinished content so we can iterate over it.

**Comment by aniagaska** [comment]
> > I wonder if there is another way we can show how much time is passing for these agencies without progress.
> 
> Too bad there's not an easy way to make a Napoleon march graph 😭
> https://en.wikipedia.org/wiki/Charles_Joseph_Minard#/media/File:Minard.png


I'll keep thinking! Maybe we can make something ourselves like we add a 1px square for every day and then you can scroll through it?

**Comment by amcguiga** [comment]
Added a new bubble graph for fees to sandbox.
Screen Shot 2021-04-13 at 7 04 10 PM

**Review by bronzehedwick — APPROVED** [review]

**Pull request merged**
