### PR TITLE
Add price filter

### PR DESCRIPTION
**Pull request by bronzehedwick**
Abstract the filtering to a function to handle multiple filters.

Re-render the filtered results instead of show/hiding (the view is
re-rendered every time anyway, so might as well remove the elements from
the DOM).

### CODE REVIEW

**Review by ashryanbeats — COMMENTED** [review]
Hi Chris,

I'm running into a couple of issues running this update. Could you have a look and let me know I might be doing wrong?

# "Same key" errors from React

I'm getting a number of errors like this in my browser console:

```
Warning: Encountered two children with the same key, `129186`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (at FoiaList.js:62)
    in div (at FoiaList.js:42)
    in FoiaList (at App.js:7)
    in div (at App.js:6)
    in App (at src/index.js:7)
    in StrictMode (at src/index.js:6)
```

I thought this could be due to duplicate IDs in the datastore, but that doesn't seem to be the case.

# Price filter not filtering

Possibly related to the above, but while the price dropdown is successfully populating, when I select a value, the UI does seem to filter, just not with the expected result.

For example, if I select "$47,504.00" as the filter, I'm left with 23 results (down from >400), but all the results have a price of $0.00. The expected result would be 1 entry with the selected price.

---

I figure you probably didn't see the same issues on your side, so I'm wondering how we can go about figuring out where the issue lies. Do you have any suggestions?

**Comment by bronzehedwick** [comment]
Hmm, yeah I am not able to replicate this locally 🤔.

To test, I re-cloned the repo, and still was not able to replicate the error.

I following these steps:

1. `git clone git@github.com:bronzehedwick/50-a-foil-status.git`
2. `git checkout cost-filter`
3. `cd 50-a-foil-status`
4. `npm -C server install`
5. `npm -C browser install`
6. `cp server/src/datastore/referenceData/fullDatastore-1597979700734.json server/src/datastore/data/1597979700734.json`
7. `npm -C server run dev`
8. `npm -C browser start`

Of possible note, my local node version is `v14.11.0`.

Also happy to jump on a call to help debug if that's useful.

**Comment by ashryanbeats** [comment]
Thanks Chris! Let me give it a spin with a fresh install first, then I'll bump my Node to v14.x. If that doesn't work, I'll reach out :)

**Comment by ashryanbeats** [comment]
I think I know what's causing it: 

Muckrock ids are strings of integers of N length. So these ids could be represented in JSON as strings or numbers. The output of my new datastore script is inconsistent with the string/number coercion from the old script. And on top of that, the old script wasn't consistent within itself in whether it stored ids as strings or numbers.

You weren't able to reproduce the issue because #8 produces the output that triggers the issue.

I _suspect_ the issue I see is surfaced by this line (caused by inconsistencies in the datastore scripts):
https://github.com/astoria-tech/50-a-foil-status/pull/7/files#diff-b65273c41f47419f265773f0e963bf6dR64

The question is around this part of that line:

```js
key={item.agency.id + item.foiaReq.id + item.jurisdiction.id}
```

Are you expecting to be able to concat strings or add numbers?

There's no wrong answer here, I just want to know whether you want strings or numbers for ids in the JSON, and I can make that change in short order.

**Comment by bronzehedwick** [comment]
> Are you expecting to be able to concat strings or add numbers?

Gotcha! That makes sense. 

I was expecting to concat strings, not adding numbers. Open to other options, but my sense was that there would be less change of collisions that way.

**Comment by ashryanbeats** [comment]
All good! I should be able to make the change in #8 today. I'll go ahead and merge this PR now and address the issue in #8.

**Pull request merged**
